### ISSUE TITLE
建议增加甲醛传感器模块

### ISSUE THREAD

**Issue by chenjuneking** [ruffjs/ruff-issues#12]
https://item.taobao.com/item.htm?spm=a230r.1.14.37.GtM457&id=522949723202&ns=1&abbucket=4#detail

**Ruff Version:**

0.9.0 / 1.0.0

**Code**

``` javascript
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**

**Actual behavior:**

**Comment by lalawuu** [comment]
已经将该设备列入考察计划，相关更新可在本 issue 里找到。

**Comment by lalawuu** [comment]
It can be included into consideration into #2 .

**Comment by vilicvane** [comment]
@aseaday 那这个 issue 可以 close 掉嘛?

**Comment by lalawuu** [comment]
close 吧
