### ISSUE TITLE
WIFI SSID中包含中文“—”，设备连接不成功

### ISSUE THREAD

**Issue by sh0rt2020** [ruffjs/ruff-issues#14]
**Ruff Version:**

0.9.0 / 1.0.0

**Code**
$ rap wifi
? SSID **_—**_

``` javascript
// A self-contained demonstration of the problem follows...

```

**Expected behavior:**
成功连接设备

**Actual behavior:**
一直在打点，开新终端执行"rap scan"，提示先执行"rap wifi"。
最终设备连接失败。

**TODO:**
- [ ] rap 支持
- [ ] cupid 支持

**Comment by zpan** [comment]
发现 SSID中包含 "\" 时，设备连接也会不成功。

**Comment by dreamhead** [comment]
Ruff 1.3 发布了，我们尝试修复了这个问题，欢迎大家测试！

[Ruff 1.3 正式发布！](http://community.ruff.io/t/ruff-1-3-ruff-ruff/391)

**Comment by zpan** [comment]
Fix on Ruff 1.3.

**Comment by sh0rt2020** [comment]
Thx
