### ISSUE TITLE
Ruff SDK 1.7.1 & 1.7.2 don't work without init

### ISSUE THREAD

**Issue by iFwu** [ruffjs/ruff-issues#20]
**Ruff Version:**
Ruff SDK 1.7.1 & 1.7.2 on macOS 10.12.4 (16E195)

**Expected behavior:**
Normal behavior.

**Actual behavior:**
In shell environment，`rap` command is totally broken which returns the following ERR info when there is no init files (package.json).
```
ERR Invalid package version.
```
Thus, I can't init a directory use `rap` command because I can't use `rap init`, that's a infinite loop.
Hope there will be more robust tests before upgrade to avoid such low-level mistakes.

**Comment by zpan** [comment]
Hi Xekri,

Could you help to check whether this is a file named package.json in your user's home directory?

If so, try to rename it and run `'rap init'` again.

**Comment by iFwu** [comment]
@blackisle All right, after renaming it, the command works.
But I still think that's not what a shell program should expect...

**Comment by zpan** [comment]
Hi Xekri,

Thanks for your reply.

We will improve it in the next release.
